name: Android CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./platform/android

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-space-invaders-debug
        path: ./platform/android/app/build/outputs/apk/debug/*.apk

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-space-invaders-debug
        path: ./platform/android/app/build/outputs/apk/release/*.apk
